app:
  storage: postgres

grpc:
  port: 8080
  gateway_port: 8081

storage:
  pool_size: 10
  timeout_ms: 1000

telegram:
  api_key: 
  timeout: 60
  offset: 0

database:
  host: localhost
  port: 5555
  user: postgres
  password: hGrfdsf@URnj
  name: homework
  
pooler:
  host: localhost
  port: 6432
  user: postgres
  password: hGrfdsf@URnj
  name: homework