version: '3'

services:
  person_service:
    environment:
      GRPC_PORT: 8080
      GRPC_GATEWAY_PORT: 8081
      STORAGE_POOL_SIZE: 10
      STORAGE_TIMEOUT_MS: 1000
      TELEGRAM_API_KEY:
      TELEGRAM_TIMEOUT: 60
      TELEGRAM_OFFSET: 0
    container_name: person_service
    build: .
    ports:
      - "127.0.0.1:8081:8081"