version: '3'

services:
  pgbouncer_homework:
    container_name: pgbouncer_homework
    image: bitnami/pgbouncer
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=postgres_homework
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=hGrfdsf@URnj
      - POSTGRESQL_DATABASE=homework
      - PGBOUNCER_DATABASE=homework
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
    depends_on:
      - postgres_homework

  postgres_homework:
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hGrfdsf@URnj
    restart: always
    container_name: postgres_homework
    image: postgres:13
    ports:
      - "127.0.0.1:5555:5432"