package main

const templ = `// Code generated by buildergen. DO NOT EDIT.

package {{.Name}}
{{range $s := .Structs}}
// -----------------------------------------------
// ---------- Builded from {{$s.Name}} 
// -----------------------------------------------
type {{$s.Name}}Builder struct {
	i *{{$s.Name}}
}

func New{{$s.Name}}Builder() *{{$s.Name}}Builder {
	return &{{$s.Name}}Builder{
		i: &{{$s.Name}}{},
	}
}

func (b *{{$s.Name}}Builder) P() *{{$s.Name}} {
	return b.i
}

func (b *{{$s.Name}}Builder) V() {{$s.Name}} {
	return *b.i
}
{{range $f := $s.Fields}}
func (b *{{$s.Name}}Builder) {{$f.Name}}(v {{$f.Type}}) *{{$s.Name}}Builder {
	b.i.{{$f.Name}} = v
	
	return b
}
{{end}}{{end}}`
