// Code generated by buildergen. DO NOT EDIT.

package main

// -----------------------------------------------
// ---------- Builded from testInnerStruct 
// -----------------------------------------------
type testInnerStructBuilder struct {
	i *testInnerStruct
}

func NewtestInnerStructBuilder() *testInnerStructBuilder {
	return &testInnerStructBuilder{
		i: &testInnerStruct{},
	}
}

func (b *testInnerStructBuilder) P() *testInnerStruct {
	return b.i
}

func (b *testInnerStructBuilder) V() testInnerStruct {
	return *b.i
}

// -----------------------------------------------
// ---------- Builded from TestInnerStruct 
// -----------------------------------------------
type TestInnerStructBuilder struct {
	i *TestInnerStruct
}

func NewTestInnerStructBuilder() *TestInnerStructBuilder {
	return &TestInnerStructBuilder{
		i: &TestInnerStruct{},
	}
}

func (b *TestInnerStructBuilder) P() *TestInnerStruct {
	return b.i
}

func (b *TestInnerStructBuilder) V() TestInnerStruct {
	return *b.i
}

// -----------------------------------------------
// ---------- Builded from testStruct 
// -----------------------------------------------
type testStructBuilder struct {
	i *testStruct
}

func NewtestStructBuilder() *testStructBuilder {
	return &testStructBuilder{
		i: &testStruct{},
	}
}

func (b *testStructBuilder) P() *testStruct {
	return b.i
}

func (b *testStructBuilder) V() testStruct {
	return *b.i
}

// -----------------------------------------------
// ---------- Builded from TestStruct 
// -----------------------------------------------
type TestStructBuilder struct {
	i *TestStruct
}

func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		i: &TestStruct{},
	}
}

func (b *TestStructBuilder) P() *TestStruct {
	return b.i
}

func (b *TestStructBuilder) V() TestStruct {
	return *b.i
}

func (b *TestStructBuilder) PublicValueInt(v int) *TestStructBuilder {
	b.i.PublicValueInt = v
	
	return b
}

func (b *TestStructBuilder) PublicValueString(v string) *TestStructBuilder {
	b.i.PublicValueString = v
	
	return b
}

func (b *TestStructBuilder) PublicValueFloat32(v float32) *TestStructBuilder {
	b.i.PublicValueFloat32 = v
	
	return b
}

func (b *TestStructBuilder) PublicValuePublicStruct(v TestInnerStruct) *TestStructBuilder {
	b.i.PublicValuePublicStruct = v
	
	return b
}

func (b *TestStructBuilder) PublicValuePrivateStruct(v testInnerStruct) *TestStructBuilder {
	b.i.PublicValuePrivateStruct = v
	
	return b
}

func (b *TestStructBuilder) PublicPointerInt(v *int) *TestStructBuilder {
	b.i.PublicPointerInt = v
	
	return b
}

func (b *TestStructBuilder) PublicPointerString(v *string) *TestStructBuilder {
	b.i.PublicPointerString = v
	
	return b
}

func (b *TestStructBuilder) PublicPointerFloat32(v *float32) *TestStructBuilder {
	b.i.PublicPointerFloat32 = v
	
	return b
}

func (b *TestStructBuilder) PublicPointerPublicStruct(v *TestInnerStruct) *TestStructBuilder {
	b.i.PublicPointerPublicStruct = v
	
	return b
}

func (b *TestStructBuilder) PublicPointerPrivateStruct(v *testInnerStruct) *TestStructBuilder {
	b.i.PublicPointerPrivateStruct = v
	
	return b
}
